### ISSUE TITLE
Add but() to builder class which returns a new builder with the current builder values

### ISSUE THREAD

**Issue by dorireuv** [mjedynak/builder-generator-idea-plugin#10]
This is very useful when you have a common base builder. An example can be found in Nat Pryce blog (search for 'but()'): http://www.natpryce.com/articles/000769.html

Scenario:
Let's say I have User class with gender and country fields. If I would like to create a user from Italy BUT a male and a user from Italy BUT a female. This can be achieved by creating a builder withCountry(Italy) and in one time but().withGender(MALE) and another but().withGender(FEMALE).

Example for but() in UserBuilder with 2 fields (country and gender):

```
public class UserBuilder {
  private Country country;
  private Gender gender;

  private UserBuilder() {
  }

  public static UserBuilder aUser() {
    return new UserBuilder();
  }

  public UserBuilder withCounter(Country country) {
    this.country = country;
    return this;
  }

  public UserBuilder withGender(Gender gender) {
    this.gender = gender;
    return this;
  }

  public UserBuilder but() {
    return aUser().withCountry(country).withGender(gender);
  }

  public User build() {
    User user = new User(country, gender);
    return user;
  }
}
```

**Comment by frankcastro** [comment]
This is a really nice method, but for the life of me, I can't understand how to use .but().  I can't seem to call it on an existing object.  An example not just the class above would be highly useful.  Thank you very much!

**Comment by frankcastro** [comment]
Hi, I'm sorry to bother you, but I can't figure out how to use the but() method.  I looked at the link you refer, but it's not really using your Builder Generator.  Would it be possible to add how to use but() to the readme?  Thank you so much.
