### ISSUE TITLE
Requires constructor already present

### ISSUE THREAD

**Issue by martypitt** [mjedynak/builder-generator-idea-plugin#11]
A fairly minor niggle in an otherwise awesome project:

It seems as though the builder requires that a constructor already be present.

When trying to use the builder with a class without a constructor, the "wizard" doesn't list any fields to use.

This makes the workflow:
 * Create a class
 * Create a constructor with a set of fields
 * Create a builder.

It'd be great not have to perform step 2.

**Comment by vramdal** [comment]
That would be one solution.

Or, in the case of an inner builder class, the builder could access the encompassing class' fields directly.
