### ISSUE TITLE
Regenerate a builder

### ISSUE THREAD

**Issue by jripault** [mjedynak/builder-generator-idea-plugin#18]
It would be nice to have a 'Regenerate builder' action, to avoid deleting the builder and recreate it.

**Comment by Helmsdown** [comment]
Agreed. Please add this!!!!

**Comment by mcbeelen** [comment]
+1

**Comment by KoenOlaerts** [comment]
This would be a very great addition!
We generally only use the fields we need for the given use case. Then on a later moment we need other fields as well. At the moment this leads us to manual actions. If it would be possible to call upon the small wizard again and select some new fields which would be added to the existing builder, that would be very nice.

Thanks

**Comment by sebastian-r** [comment]
+1

**Comment by gauravsak** [comment]
@jripault What happens if you regenerate the builder and Idea prompts you that the class already exists? Just overwrite it with the new file.

**Comment by sothawo** [comment]
this issue is quite old now, would be great if it could be addressed.

**Comment by mkickax** [comment]
@mjedynak, What would be the workflow for this feature? I suggest the following scenarios:

1. using CTRL+SHIFT+ALT+B from the class needing builder update or from the builder itself 
2. open the member chooser with fields already existing preselected
3. empty the existing builder and recreate everything according to the fields selected in the previous popup

=> Drawbacks, we need code to find out what's the prefix to be used and if but method needs to be recreated. It's not possible to add but method during update if it was not created during first creation.

1. using CTRL+SHIFT+ALT+B from the class needing builder update or from the builder itself 
2. open the member chooser with only fields missing in the current builder
3. add to the existing builder the fields selected in the previous popup

=> Drawbacks, we need code to find out what's the prefix to be used and maybe sort the methods.  It's not possible to add but method during update if it was not created during first creation.

1. using CTRL+SHIFT+ALT+B from the class needing builder update or from the builder itself 
2. open a first popup with prefix input field and but method option (it can be the same popup as for first creation with others fields already filled in and greyed out)
2. open the member chooser with fields already existing preselected
3. empty the existing builder and recreate everything according to the fields selected in the previous popup

=> Drawbacks, longer workflow with an extra popup

**Comment by mjedynak** [comment]
I wouldn't like to lose the ability to go to already existing builder with CTRL+SHIFT+ALT+B, so I was thinking that regenerating would have its own shortcut.
As a first step, I wouldn't read the state of existing builder but just display the same dialog as for a new builder and replace the existing one if user completed the wizard.
Does anyone have any suggestion, comments?

**Comment by mkickax** [comment]
I agree with you, I don't want to lose the "go to" feature, that's why I was suggesting CTRL+SHIFT+ALT+B for builder update, since for creation and "go to" we use SHIFT+ALT+B.

What you propose is to keep the same workflow for update as for creation, with an automatic and systematic deletion of the former builder.
=> Drawbacks, if the user input different name, package or prefix for new builder, all previous usages of the builder will be KO (in my opinion adding new fields manually to the existing builder is safer). Besides trying to inspect the existing builder to guess the prefix is not that easy, even more if there was manual changes meanwhile.
