### ISSUE TITLE
What is but method?

### ISSUE THREAD

**Issue by yonesko** [mjedynak/builder-generator-idea-plugin#46]
It seems useless.

Second question: do you have prototype builder? EntityBuilder that sets filelds in its constructor from  Entity?

**Comment by BehindTheFacade** [comment]
MyObjectBuilder builder = new MyObjectBuilder.aObject().withThis("this").withThat("that");
MyObject firstObject = builder.build();
MyObject secondObject = builder.but().withThis("this_property_is_different_but_that_property_is_the_same").build()

Just allows you to essentially create multiple objects from the same base builder, but, with some different properties.
