### ISSUE TITLE
Plugin prevents IDEA from shutdown

### ISSUE THREAD

**Issue by diversit** [mjedynak/builder-generator-idea-plugin#75]
The plugin prevents IDEA from a normal shutdown/stop. On Mac it requires a force-quit to actually stop IDEA.
Perhaps just a bug somewhere, but since it might indicate some suspicious process running preventing IDEA to shutdown I removed it.

After plugin removable IDEA shutdown down normally again.

**Comment by martinariehm** [comment]
Same happens on Linux (Ubuntu 22.04 LTS).

**Comment by martinariehm** [comment]
The issue seems to have been fixed with the latest releases of idea and builder-generator.
